config/routes.rb
Rails.application.routes.draw do
  root 'pokemons#index'
  devise_for :users
  resources :pokemons, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:index, :new, :create]
  end
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  
  validates :name, presence: true
  validates :ability, presence: true
  validates :poketype, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :pokemon

  validates :body, presence: true
  validates :rating, numericality: {
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  validates :pokemon, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
before_action :authenticate_user!

  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @reviews = @pokemon.reviews
    @review = Review.new
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.user = current_user
    
    if @pokemon.save
      flash[:notice] = "Pokemon successfully added!"
      redirect_to pokemons_path
    else
      flash[:errors] = @pokemon.errors.full_messages.join(". ")
      render :new
    end
  end

  private
  def pokemon_params
    params.require(:pokemon).permit(:name, :ability, :poketype, :strength, :age, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @pokemon = Pokemon.find(params[:pokemon_id])
    @review = Review.new(review_params)
    @review.pokemon = @pokemon
    @review.user = current_user

    if @review.save
      flash[:notice] = "Review added"
      redirect_to pokemon_path(@pokemon)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      render "pokemons/show"
    end
  end

  private
  def review_params
    params.require(:review).permit(:body, :rating, :user_id, :pokemon_id)
  end
end

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemon Reviews</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Pokemon Reviews</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Hi #{current_user.first_name}", edit_user_registration_path %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

    <div class="row">
      <% flash.keys.each do |type| %>
        <% flash[type].split(":( ").each do |f| %>
          <div data-alert class="flash <%= type %> alert-box radius">
              <%= f %>
            <a href="#" class="close">&times;</a>
          </div>
        <% end %>
      <% end %>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/pokemons/index.html.erb
<div class="clearfix">

<h1 class="left">Pokedex</h1>
<div class="right add-new">
  <%= link_to "Add New Pokemon to your Pokedex", new_pokemon_path, class: "button" %>
</div>
</div>

<% @pokemons.each do |pokemon| %>
<div class="panel">
  <%= link_to pokemon.name, pokemon_path(pokemon) %>
</div>
<% end %>

app/views/pokemons/new.html.erb
<h1>Add your Pokemon to your Pokedex</h1>

<div class="row">
<%= form_for @pokemon do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :ability %>
  <%= f.text_field :ability %>

  <%= f.label :poketype %>
  <%= f.text_field :poketype %>

  <%= f.label :strength %>
  <%= f.text_field :strength %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit "Add Pokemon", class: 'button' %>

<% end %>
</div>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>
<div class="clearfix">
  <div class="stats panel right">
    <h2 class="center">Stats</h2>
    <ul>
      <li><span>Age:</span> <%= @pokemon.age %></li>
      <li><span>Strength:</span> <%= @pokemon.strength %></li>
      <li><span>Ability:</span> <%= @pokemon.ability.capitalize %></li>
      <li><span>Type:</span> <%= @pokemon.poketype.capitalize %></li>
    </ul>
  </div>
  <div class="left">
    <%= image_tag("psyduck.png") %>
  </div>
</div>

<%= form_for [@pokemon, @review] do |f| %>
  <%= f.label :body, "Leave a review" %>
  <%= f.text_field :body %>

  <%= f.label :rating, "Rating (scale of 1 - 5)" %>
  <%= f.text_field :rating %>

  <%= f.submit "Add Review", class: "button" %>
<% end %>

<h2>Reviews</h2>
  <% if @reviews.present? %>
    <% @reviews.each do |review| %>
      <div class="reviews panel">
        <ul>
          <li>Rating: <%= review.rating %></li>
          <li>Review: <%= review.body %></li>
        </ul>
      </div>
    <% end %>
  <% end %>